-- Meme Studio: GIF template library
-- Run this in Supabase SQL Editor.
create table if not exists public.gif_templates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  image_url text not null,
  thumbnail_url text,
  description text,
  category text not null default 'popular',
  width integer,
  height integer,
  sort_order integer not null default 100,
  active boolean not null default true
);

alter table public.gif_templates enable row level security;

drop policy if exists "Public can read GIF templates" on public.gif_templates;
create policy "Public can read GIF templates"
on public.gif_templates
for select
to public
using (active = true);

create index if not exists gif_templates_category_idx on public.gif_templates(category);
create index if not exists gif_templates_sort_order_idx on public.gif_templates(sort_order, id);

-- Optional: use Supabase Storage for the GIF files. A public bucket named gif-templates
-- keeps image_url/thumbnail_url stable and CORS-friendly for the browser editor.
-- After creating the bucket, set image_url to the public object URL.
